# Generated by Django 6.0.1 on 2026-02-05 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='tipo de pipa')),
            ],
            options={
                'verbose_name': 'Tipo de Pipa',
                'verbose_name_plural': 'Tipos de Pipa',
                'db_table': 'tipo_pipa',
            },
        ),
        migrations.CreateModel(
            name='Pipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pipa', models.CharField(blank=True, db_column='no_pipa', max_length=20, verbose_name='número de pipa')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='placa de la pipa')),
                ('capacidad', models.PositiveIntegerField(verbose_name='capacidad de la pipa (en litros)')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio', verbose_name='servicio al que pertenece la pipa')),
                ('tipo_pipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportes.tipopipa', verbose_name='tipo de pipa')),
            ],
            options={
                'verbose_name': 'Pipa',
                'verbose_name_plural': 'Pipas',
                'db_table': 'pipa',
            },
        ),
    ]
