# Generated by Django 6.0.1 on 2026-02-05 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de la evidencia')),
                ('entrega_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.entregadiaria', verbose_name='entrega diaria relacionada')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencia',
            },
        ),
        migrations.CreateModel(
            name='ImagenEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tmp/', verbose_name='imagen')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='seguimiento.evidencia', verbose_name='evidencia')),
            ],
            options={
                'verbose_name': 'Imagen de Evidencia',
                'verbose_name_plural': 'Imágenes de Evidencias',
                'db_table': 'imagen_evidencia',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='contenido del reporte')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora del reporte')),
                ('entrega_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.entregadiaria', verbose_name='entrega diaria relacionada')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='ImagenReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tmp/', verbose_name='imagen')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='seguimiento.reporte', verbose_name='reporte')),
            ],
            options={
                'verbose_name': 'Imagen de Reporte',
                'verbose_name_plural': 'Imágenes de Reportes',
                'db_table': 'imagen_reporte',
            },
        ),
        migrations.CreateModel(
            name='RespuestaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(verbose_name='respuesta al reporte')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de la respuesta')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.reporte', verbose_name='reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario que responde')),
            ],
            options={
                'verbose_name': 'Respuesta de Reporte',
                'verbose_name_plural': 'Respuestas de Reportes',
                'db_table': 'respuesta_reporte',
            },
        ),
    ]
