# Generated by Django 6.0.1 on 2026-02-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='apellido paterno')),
                ('apellido_m', models.CharField(blank=True, max_length=100, verbose_name='apellido materno')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='usuario activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
