# Generated by Django 6.0.1 on 2026-02-05 05:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('servicio', '__first__'),
        ('transportes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre de la prioridad')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
                'db_table': 'prioridad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='tipo de entrega')),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
                'verbose_name_plural': 'Tipos de Entrega',
                'db_table': 'tipo_entrega',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_entrega', models.CharField(max_length=20, unique=True, verbose_name='folio de entrega')),
                ('direccion', models.CharField(max_length=250, verbose_name='dirección de entrega')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitud')),
                ('fecha_entrega', models.DateField(default=datetime.date.today, verbose_name='fecha de entrega')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono de contacto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('pipa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.pipa', verbose_name='pipa asignada')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicio.servicio', verbose_name='servicio asociado')),
                ('tipo_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoagua', verbose_name='tipo de agua')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.prioridad', verbose_name='prioridad')),
                ('tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.tipoentrega', verbose_name='tipo de entrega')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='EntregaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha del dia de entrega')),
                ('estatus', models.BooleanField(default=False, verbose_name='estatus de la entrega')),
                ('comentarios', models.TextField(blank=True, verbose_name='comentarios adicionales')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entregas.entrega', verbose_name='entrega')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='repartidor')),
            ],
            options={
                'verbose_name': 'Entrega Diaria',
                'verbose_name_plural': 'Entregas Diarias',
                'db_table': 'entrega_diaria',
                'constraints': [models.UniqueConstraint(fields=('entrega',), name='unique_entrega_en_entrega_diaria')],
            },
        ),
    ]
